### ISSUE TITLE
Change YAML format to Avram specification

### ISSUE THREAD

**Issue by nichtich** [sul-dlss/marctable#1]
[Avram specification](https://format.gbv.de/schema/avram/specification) is still being worked on to get to 1.0.0 but the core parts are settled. With [this pull request](https://github.com/timathom/marc-schema/pull/12) there is also another scraper to convert MARC21 specification from HTML to Avram. [This script](https://www.npmjs.com/package/avram#avram-validate-schema) can be used to check whether a JSON file is valid Avram. Differences to the current YAML format:

- Wrap list of fields in root element `fields:`
- Rename `name` to `label`
- Remove empty `subfields: []` for fixed fields
- Use object instead of array for lists of fields and for lists of subfields

Expected format like this:

~~~yaml
fields:
  001:
    label: Control Number
    repeatable: false
    tag: '001' # optional
  010:
    label: Library of Congress Control Number
    repeatable: false
    tag: '010' # optional
    subfields:
      a:
        code: a # optional
        label: LC control number
        repeatable: false
      b:
        code: b # optional
        label: NUCMC control number
        repeatable: true
      z:
        code: z # optional
        label: Canceled/invalid LC control number
        repeatable: true
      8: 
        code: '8' # optional
        label: Field link and sequence number
        repeatable: true
~~~

**Comment by edsu** [comment]
This is a great idea, and one that must have been bubbling in my subconscious since I had looked at Avram recently!
