### ISSUE TITLE
Improperly named project

### ISSUE THREAD

**Issue by riordan** [sul-dlss/marctable#2]
For anything that is extracting MARC with Parquet as a first-class-citizen, the name MARCquet is _right there!_

Sorry for the trolling; this is genuinely awesome and has me very excited for complete catalogs (and meta catalogs) that ship with portable data warehouses.

**Comment by edsu** [comment]
Yay! That is a better name, but since it does more than parquet I still prefer marctable :-) 

Please keep the suggestions coming!
